[package]
name = "merkle-methods-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
# NOTE: ethabi is used here instead of ethers because ethers requires getrandom support.
ethabi = { version = "18.0", default-features = false }
# Must match RISC Zero version specified in the project root.
risc0-zkvm = { path = "../../../../risc0/zkvm", default-features = false }
tiny-keccak = { version = "2.0", features = ["keccak"] }
rs_merkle = { version = "1.4", default-features = false }

[profile.release]
lto = true
opt-level = 3
